### ISSUE TITLE
passport.use(new OktaStrategy results in TypeError: OktaStrategy is not a constructor

### ISSUE THREAD

**Issue by jennifer-galvin** [techstars/passport-okta-oauth#1]
Using the example as stated (and defining passport) results in the following error:  TypeError: OktaStrategy is not a constructor

Go to https://npm.runkit.com/passport-okta-oauth, using the example code (and filling in the passport requirements and substituting baseURL) this is the resulting error

----------------------------------

var passport = require("passport");
var passportOktaOauth = require("passport-okta-oauth")

passport.use(new passportOktaOauth({
  audience: process.env.OKTA_AUDIENCE,   
    // audience is the Okta Domain, 
    // e.g. https://example.okta.com, https://example.oktapreview.com
    
  clientID: process.env.OKTA_CLIENTID,
    // clientID is the public Okta Application Client Credentials, 
    // its a 20 character alphanumeric string
    // e.g. U7VYvsaiuqlDOHjIVTIA  (generated example)

  clientSecret: process.env.OKTA_CLIENTSECRET,
    // clientSecret is the private Okta Application Client Credentials, 
    // its a 40 character alphanumeric string with a hypen(s).
    // e.g. Vwb-R4fQnSH7uJkokDhPI-WR4qEiuWFokYANM5C  (generated example)
    
  idp: process.env.OKTA_IDP,
    // idp is the Identity Provider (id). This is an optional field
    // its a 20 character alphanumeric string
    // e.g. qOp8aaJmCEhvep5Il6ZJ  (generated example)
    
  scope: ['openid', 'email', 'profile'],
  response_type: 'code',
  callbackURL: "http://localhost" + "/auth/okta/callback"
    // callbackURL is the redirect URL Okta should return the user to
    // This is a URL on your server
    
}, function(accessToken, refreshToken, profile, done) {
  // Example Callback to Handle the Profile Object

  return profile
}));

----------------------------------

**Comment by whereisciao** [comment]
Sorry you are having issues. Thank you for dealing with my rough instructions. Try adjust your `require` syntax to the following below. 

```
OktaStrategy = require('passport-okta-oauth').Strategy
```

**Comment by jennifer-galvin** [comment]
Thank you - I should have tried that ;-)
